# Generated by Django 4.2.30 on 2026-04-25 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=255, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resumo', models.TextField()),
                ('data_geracao', models.DateTimeField(auto_now=True)),
                ('pesquisa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumo_ia', to='tracker.pesquisa')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('resumo', models.TextField()),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('data_publicacao', models.DateTimeField()),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='tracker.pesquisa')),
            ],
        ),
        migrations.CreateModel(
            name='AnaliseSentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEUTRO', 'Neutro'), ('NEGATIVO', 'Negativo')], max_length=20)),
                ('pontuacao', models.FloatField(default=0.0)),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise', to='tracker.noticia')),
            ],
        ),
    ]
