# Generated by Django 4.2.30 on 2026-04-25 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=255)),
                ('setor', models.CharField(choices=[('TECH', 'Tecnologia'), ('RETAIL', 'Varejo'), ('FINANCE', 'Finanças'), ('AGRO', 'Agronegócio'), ('OTHER', 'Outro')], max_length=20)),
                ('dor_monitoramento', models.IntegerField(help_text='O quanto o monitoramento manual de marcas é um problema?')),
                ('importancia_sentimento', models.IntegerField(help_text='Qual a importância de saber o sentimento do público em tempo real?')),
                ('necessidade_ia', models.IntegerField(help_text='O quanto resumos automáticos via IA agregariam valor?')),
                ('frequencia_crise', models.IntegerField(help_text='Com que frequência a marca enfrenta crises de imagem?')),
                ('score_aderencia', models.FloatField(default=0.0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
